# Generated by Django 3.2.11 on 2022-02-04 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(max_length=10000)),
                ('token', models.CharField(default='7485a99fc8f2e775a4928c9474806a447a53f6d9', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='chatlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userIP', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('ended', models.DateTimeField()),
                ('messages', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=200)),
                ('ans', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('avatar', models.ImageField(default='chicken.jpg', upload_to='avatars/')),
                ('info', models.TextField(default='N\\A', max_length=200)),
                ('username', models.CharField(default='#user', max_length=200)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('credits', models.IntegerField(default=100)),
                ('bots', models.ManyToManyField(to='profiles.ChatbotProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatbotprofile',
            name='faqs',
            field=models.ManyToManyField(to='profiles.faq'),
        ),
        migrations.AddField(
            model_name='chatbotprofile',
            name='logs',
            field=models.ManyToManyField(to='profiles.chatlog'),
        ),
        migrations.AddField(
            model_name='chatbotprofile',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Connected_User', to=settings.AUTH_USER_MODEL),
        ),
    ]
