# Generated by Django 3.2.11 on 2022-02-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20220204_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotprofile',
            name='token',
            field=models.CharField(default='2a5124b0-0f44-4ac5-b9bb-7959a0c7a0ea', max_length=100),
        ),
    ]
