# Generated by Django 3.2.11 on 2022-02-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_chatbotprofile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotprofile',
            name='token',
            field=models.CharField(max_length=100),
        ),
    ]
