# Generated by Django 3.2.11 on 2022-02-04 16:24

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_chatbotprofile_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbotprofile',
            name='token',
            field=models.CharField(default=profiles.models.ChatbotProfile.generateToken, max_length=100),
        ),
    ]
