# Generated by Django 3.2.11 on 2022-02-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_chatbotprofile_greeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlog',
            name='cost',
            field=models.FloatField(default=0),
        ),
    ]
