# Generated by Django 3.2.11 on 2022-02-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_chatlog_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='credits',
            field=models.FloatField(default=100),
        ),
    ]
